[package]
name = "taterfs-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["fs"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
tempfile = "3"
